### ISSUE TITLE
Allow edits to person without requiring an Evaluation

### ISSUE THREAD

**Issue by judieschu** [BrandNewCongress/candidate-evaluator#4]
Users may make some edits to the person - profile, links, etc. - but not ready to complete the evaluation.  Allow user to Submit changes without requiring an Evaluation.  Move to the next available Person, or return to the Main Screen if no additional evaluations for that user.

**Comment by ben-pr-p** [comment]
Ok so, I will only force edits to the profile if there is a new evaluation?

**Comment by judieschu** [comment]
Yes - only when a new eval is added.
