### ISSUE TITLE
Nice to have: Show a running total of evaluations completed this week.

### ISSUE THREAD

**Issue by judieschu** [BrandNewCongress/candidate-evaluator#9]
Nice to have this if it's a small effort and creates minimal additional latency in loading the page.
On the main page, display: "Evaluations you completed this week: XX"
Data should reset end of day Sunday.
If possible, also add: "Evaluations completed by the team this week: XX"

**Comment by ben-pr-p** [comment]
Hey Judie – this is in the domain of the upcoming dashboard, which me and a few other devs will start work on at the beginning of next week
